name: CI Build
on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.gitignore'
      - 'README.md'
    types:
      - 'closed'
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
    paths-ignore:
      # - '.github/**'
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    env:
      ACCOUNT: ${{ secrets.AWS_ACCOUNT_TINYBEANS }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: 'Checkout to $GITHUB_WORKSPACE'
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: "arn:aws:iam::375215620020:role/aws-ci-ec2-role"
          role-duration-seconds: 1200
          role-session-name: CI-${{ github.run_number }}

      - name: Docker ECR login
        run: docker login -u AWS -p $(aws ecr get-login-password --region us-west-2) $ACCOUNT.dkr.ecr.us-west-2.amazonaws.com

      - name: Create ECR if needed
        run: aws ecr create-repository --repository-name tinybeans/$REPO_NAME || true

      - name: SHA
        run: echo "SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      # - name: Check SHA
      #   run: echo $SHA

      - name: Docker build
        run: docker build -f docker/base/Dockerfile -t $REPO_NAME docker/base

      - name: Docker tags
        run: >
          docker tag $REPO_NAME:latest $ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/tinybeans/$REPO_NAME:$SHA &&
          docker tag $REPO_NAME:latest $ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/tinybeans/$REPO_NAME:latest

      - name: Docker push
        run: >
          docker images && docker push $ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/tinybeans/$REPO_NAME:$SHA &&
          docker push $ACCOUNT.dkr.ecr.us-west-2.amazonaws.com/tinybeans/$REPO_NAME:latest
